# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['top' 'top' '4.5' 'top' 'top' '4.5' 'top' 'top' '2' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
def gaenerate_random_number(max_num):
    return np.random.choice(max_num,1)

print(f'Випадкова цифра: {int(gaenerate_random_number(10))}')

Випадкова цифра: 3


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [4]:
def gaenerate_random_matrix(max_num):
    return np.random.choice(max_num,(4,6))

print(f'Випадкова матриця: \n{gaenerate_random_matrix(10)}')

Випадкова матриця: 
[[5 7 6 6 9 0]
 [5 8 1 4 6 7]
 [1 6 9 2 2 4]
 [3 0 8 3 3 9]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 4 0 3 4 0 0 1 4 1]


Згенеруйте одну випадкову цифру.

In [6]:
print(f'Випадкова цифра: {np.random.randint(10)}')


Випадкова цифра: 4


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [7]:
print(f'Випадкова матриця: \n{np.random.randint(10,100, size = (4,5))}')



Випадкова матриця: 
[[83 83 77 27 23]
 [54 10 75 19 77]
 [99 89 50 65 66]
 [75 24 63 64 76]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.5262135665311842


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [9]:
size = (3,4)
print(np.random.sample(size=size))



[[0.17539676 0.39967989 0.68959279 0.63743291]
 [0.6842483  0.15121446 0.90279326 0.10062365]
 [0.15854313 0.17769168 0.74930473 0.58040007]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [11]:
size = (10,)
print((b - a) * np.random.sample(size=size) + a)

[4.89979505 3.83971347 3.40883441 3.30591099 3.82649555 4.47016034
 3.55815794 3.48024392 4.18049402 3.03679777]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[2 6 0 3 9 5 1 8 4 7]


Перетасуйте матрицю $M$.

In [13]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
np.random.shuffle(M)
print(M)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]
 [15 16 17 18 19]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [20]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [21]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [22]:
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

50 heads and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [23]:
np.random.seed(None)
tosses = np.random.choice(["H","T"], size=100)

heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

48 heads and 52 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
size = 100
a = -1
b = 1
tosses = np.zeros(100) < (b - a) * np.random.sample(size=size) + a

heads = list(tosses).count(True)
tails = list(tosses).count(False)

print("{} heads and {} tails".format(heads,tails))

60 heads and 40 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [25]:
n= [10,50,100,250,500,1000,2500,5000,10000]

def task1(n):
    tosses=np.random.choice(["H","T"], size=n)
    heads = list(tosses).count("H")

    print("Підкидань: {}\nЙмовірність: {}".format(n,heads/n), end = '\n\n')

for i in n:
    task1(i)

Підкидань: 10
Ймовірність: 0.2

Підкидань: 50
Ймовірність: 0.48

Підкидань: 100
Ймовірність: 0.43

Підкидань: 250
Ймовірність: 0.528

Підкидань: 500
Ймовірність: 0.496

Підкидань: 1000
Ймовірність: 0.476

Підкидань: 2500
Ймовірність: 0.52

Підкидань: 5000
Ймовірність: 0.5038

Підкидань: 10000
Ймовірність: 0.5051



## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [26]:
size = 60
tosses=np.random.choice(np.arange(1,7), size=size)

for i in range(1,7):
    res = list(tosses).count(i)
    print("Грань: {}\nЙмовірність: {}".format(i,res/size), end = '\n\n')


Грань: 1
Ймовірність: 0.1

Грань: 2
Ймовірність: 0.23333333333333334

Грань: 3
Ймовірність: 0.06666666666666667

Грань: 4
Ймовірність: 0.2

Грань: 5
Ймовірність: 0.16666666666666666

Грань: 6
Ймовірність: 0.23333333333333334



### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [27]:
n= [10,50,100,250,500,1000,2500,5000,10000]

def task2(n):
    tosses=np.random.choice(np.arange(1,7), size=n)

    for i in range(1,7):
        res = list(tosses).count(i)
        print("Грань: {}\nЙмовірність: {}".format(i,res/n), end = '\n')

for i in n:
    task2(i)
    print('\n')

Грань: 1
Ймовірність: 0.3
Грань: 2
Ймовірність: 0.2
Грань: 3
Ймовірність: 0.0
Грань: 4
Ймовірність: 0.2
Грань: 5
Ймовірність: 0.3
Грань: 6
Ймовірність: 0.0


Грань: 1
Ймовірність: 0.14
Грань: 2
Ймовірність: 0.22
Грань: 3
Ймовірність: 0.12
Грань: 4
Ймовірність: 0.22
Грань: 5
Ймовірність: 0.16
Грань: 6
Ймовірність: 0.14


Грань: 1
Ймовірність: 0.26
Грань: 2
Ймовірність: 0.17
Грань: 3
Ймовірність: 0.11
Грань: 4
Ймовірність: 0.21
Грань: 5
Ймовірність: 0.14
Грань: 6
Ймовірність: 0.11


Грань: 1
Ймовірність: 0.116
Грань: 2
Ймовірність: 0.144
Грань: 3
Ймовірність: 0.212
Грань: 4
Ймовірність: 0.192
Грань: 5
Ймовірність: 0.172
Грань: 6
Ймовірність: 0.164


Грань: 1
Ймовірність: 0.164
Грань: 2
Ймовірність: 0.164
Грань: 3
Ймовірність: 0.172
Грань: 4
Ймовірність: 0.15
Грань: 5
Ймовірність: 0.164
Грань: 6
Ймовірність: 0.186


Грань: 1
Ймовірність: 0.157
Грань: 2
Ймовірність: 0.159
Грань: 3
Ймовірність: 0.171
Грань: 4
Ймовірність: 0.174
Грань: 5
Ймовірність: 0.176
Грань: 6
Ймовірність: 0.163


Грань

## 5 Колода карт
### 5.1 Реалізація

In [28]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('10', '♠'), ('10', '♢'), ('10', '♡'), ('10', '♣'), ('6', '♠'), ('6', '♢'), ('6', '♡'), ('6', '♣'), ('1', '♠'), ('1', '♢'), ('1', '♡'), ('1', '♣'), ('8', '♠'), ('8', '♢'), ('8', '♡'), ('8', '♣'), ('Q', '♠'), ('Q', '♢'), ('Q', '♡'), ('Q', '♣'), ('5', '♠'), ('5', '♢'), ('5', '♡'), ('5', '♣'), ('2', '♠'), ('2', '♢'), ('2', '♡'), ('2', '♣'), ('9', '♠'), ('9', '♢'), ('9', '♡'), ('9', '♣'), ('3', '♠'), ('3', '♢'), ('3', '♡'), ('3', '♣'), ('K', '♠'), ('K', '♢'), ('K', '♡'), ('K', '♣'), ('J', '♠'), ('J', '♢'), ('J', '♡'), ('J', '♣'), ('7', '♠'), ('7', '♢'), ('7', '♡'), ('7', '♣'), ('4', '♠'), ('4', '♢'), ('4', '♡'), ('4', '♣')]


In [29]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

10♠, 10♢, 10♡, 10♣, 6♠, 6♢, 6♡, 6♣, 1♠, 1♢, 1♡, 1♣, 8♠, 8♢, 8♡, 8♣, Q♠, Q♢, Q♡, Q♣, 5♠, 5♢, 5♡, 5♣, 2♠, 2♢, 2♡, 2♣, 9♠, 9♢, 9♡, 9♣, 3♠, 3♢, 3♡, 3♣, K♠, K♢, K♡, K♣, J♠, J♢, J♡, J♣, 7♠, 7♢, 7♡, 7♣, 4♠, 4♢, 4♡, 4♣


In [30]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♠10, ♠6, ♠1, ♠8, ♠Q, ♠5, ♠2, ♠9, ♠3, ♠K, ♠J, ♠7, ♠4
♢10, ♢6, ♢1, ♢8, ♢Q, ♢5, ♢2, ♢9, ♢3, ♢K, ♢J, ♢7, ♢4
♡10, ♡6, ♡1, ♡8, ♡Q, ♡5, ♡2, ♡9, ♡3, ♡K, ♡J, ♡7, ♡4
♣10, ♣6, ♣1, ♣8, ♣Q, ♣5, ♣2, ♣9, ♣3, ♣K, ♣J, ♣7, ♣4


In [31]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('1', '♡'), ('2', '♣'), ('2', '♡'), ('7', '♢'), ('10', '♣'), ('Q', '♢'), ('8', '♣'), ('9', '♢'), ('6', '♠'), ('K', '♠'), ('9', '♡'), ('4', '♠'), ('6', '♣'), ('2', '♢'), ('7', '♣'), ('K', '♣'), ('K', '♢'), ('3', '♣'), ('3', '♢'), ('5', '♠'), ('3', '♠'), ('5', '♣'), ('1', '♢'), ('6', '♡'), ('5', '♡'), ('2', '♠'), ('8', '♠'), ('Q', '♡'), ('Q', '♠'), ('J', '♡'), ('J', '♠'), ('7', '♠'), ('4', '♡'), ('1', '♣'), ('5', '♢'), ('8', '♢'), ('1', '♠'), ('J', '♣'), ('9', '♠'), ('J', '♢'), ('10', '♡'), ('Q', '♣'), ('8', '♡'), ('10', '♢'), ('10', '♠'), ('4', '♣'), ('4', '♢'), ('3', '♡'), ('6', '♢'), ('7', '♡'), ('K', '♡'), ('9', '♣')]


In [32]:
Cards_t = [el[0] for el in Cards]
tosses=np.random.choice(Cards_t, size=10)
print(tosses)
count = 0
for card in tosses:
    if card.isdigit():
        if int(card)%2 == 0:
            count += 1
    
print("Підкидань: {}\nЙмовірність: {}".format(10,count/10), end = '\n\n')

['10' '2' '1' '1' '6' '9' '4' '4' '6' '1']
Підкидань: 10
Ймовірність: 0.6



### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [33]:
n= [10,50,100,250,500,1000,2500,5000,10000]
Cards_t = [el[0] for el in Cards]

def task3(n):
    tosses=np.random.choice(Cards_t, size=n)
    
    count = 0
    for card in tosses:
        if card.isdigit():
            if int(card)%2 == 0:
                count += 1
    
    print("Підкидань: {}\nЙмовірність: {}".format(n,count/n), end = '\n\n')

for i in n:
    task3(i)

Підкидань: 10
Ймовірність: 0.4

Підкидань: 50
Ймовірність: 0.44

Підкидань: 100
Ймовірність: 0.39

Підкидань: 250
Ймовірність: 0.372

Підкидань: 500
Ймовірність: 0.408

Підкидань: 1000
Ймовірність: 0.387

Підкидань: 2500
Ймовірність: 0.3944

Підкидань: 5000
Ймовірність: 0.3762

Підкидань: 10000
Ймовірність: 0.3908



### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [37]:
Ranks = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
Suits = ['♢', '♠', '♣', '♡']
main_list = [[(suit+rank) for rank in Ranks] for suit in Suits]

class Cards:
    def __init__(self):
        self.Ranks = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
        self.Suits = ['♢', '♠', '♣', '♡']
        lst = [False]*4
        self.Suits_qe = np.random.choice(Suits, size=4, replace=False)
        self.main_list = [[(suit+rank) for rank in Ranks] for suit in self.Suits]
        
    def step(self):
        str = ''
        s = np.random.choice(list(self.Suits_qe.keys()), size=1, replace=False)
        for i in range(4):
            card = np.random.choice(self.Ranks, size=1)
            del self.Suits[self.Suits.index(s)]
        
        del self.Suits[self.Suits.index(s)]
        Suits = np.random.choice([el for el in self.Suits_qe if el != s], size=3, replace=False)
        
        

print(main_list)

def task4():
    s = np.random.choice(np.arange(4), size=4, replace=False)
    str = np.array2string(np.random.choice(main_list[s[0]], size=4, replace=False), separator=', ', suppress_small=True)[1:-1]
    for i in range(1,4):
        str += ', ' + np.array2string(np.random.choice(main_list[s[i]], size=4, replace=False), separator=', ', suppress_small=True)[1:-1]
    for el in str.split():
        for i in range(4):
            main_list[i].remove
    
    return str
    
for _ in range(3):
    print(task4())

[['♢1', '♢2', '♢3', '♢4', '♢5', '♢6', '♢7', '♢8', '♢9', '♢10', '♢J', '♢Q', '♢K'], ['♠1', '♠2', '♠3', '♠4', '♠5', '♠6', '♠7', '♠8', '♠9', '♠10', '♠J', '♠Q', '♠K'], ['♣1', '♣2', '♣3', '♣4', '♣5', '♣6', '♣7', '♣8', '♣9', '♣10', '♣J', '♣Q', '♣K'], ['♡1', '♡2', '♡3', '♡4', '♡5', '♡6', '♡7', '♡8', '♡9', '♡10', '♡J', '♡Q', '♡K']]
'♢Q', '♢8', '♢5', '♢3', '♣8', '♣3', '♣7', '♣5', '♠4', '♠1', '♠K', '♠7', '♡2', '♡10', '♡Q', '♡7'
'♡7', '♡Q', '♡K', '♡9', '♠6', '♠K', '♠Q', '♠10', '♢5', '♢K', '♢2', '♢3', '♣5', '♣2', '♣J', '♣7'
'♠10', '♠4', '♠3', '♠6', '♢2', '♢10', '♢6', '♢9', '♡7', '♡2', '♡5', '♡10', '♣7', '♣6', '♣J', '♣2'


In [ ]:
from itertools import combinations

A = combinations(list(range(1,21)),10)
B = []

res = []

for a in A:
    for i in range(0,10):
        for j in range(0,10):
            if i!=j:
                c = a[i] + a[j]
                B.append(c)
    res.append(len(set(B)))

print(min(res))
print(max(res))

In [35]:
np.array2string(np.random.choice(np.arange(4), size=4), separator=', ', suppress_small=True)[1:-1]

'0, 3, 3, 1'

### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

